apiVersion: v1
kind: Service
metadata:
  name: goland-ia-frontend-service
  namespace: goland-ia
  labels:
    app: goland-ia-frontend
spec:
  type: ClusterIP
  selector:
    app: goland-ia-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http

